# Sampling Plan

In [20]:
import numpy as np
import scipy
import math as m


class samplingplan():
    def __init__(self):
        self.samplingplan = []
    
    
    def rlh(n,k,Edges=0):
      #  if *kwargs < 3:  # if only two arguments are passed into the method, then no egde
       #     Edges = 0
        
        X = np.zeros(n,k)
        
        for i in range(1,k):
            X(:,i) = np.transpose(np.random.permutation(np.arange(1,n+1,1))
        
        if Edges == 1:
            X = (X-1)/(n-1)
        else
            X = (X-0.5)/n
        return X     
                                  


SyntaxError: invalid syntax (<ipython-input-20-1e4478020a07>, line 12)

In [68]:
def fullfactorial(q,Edges=1):
    
    if(min(q)):
        raise Exception('You must have at least two points per dimension')
        
    n = np.prod(q)
    k = np.length(q)
    X = np.zeros(n,k)
    
    q[k+1] = 1
    
    for j in range(1,k):
        if Edges==1:
            one_d_slice = map(lambda x: x/10.0, range(0, (10/q(j) -1)+1, 10))
        else:
            one_d_slice = map(lambda x: x/10.0, range(10/q(j)/2, (10/q(j))+1, 10))
            
        column = []
        
        while np.length(column) < n:
            for l in range(1,q(j)):
                column = [column;np.ones(np.prod(range(q(j+1),k)),1)*one_d_slice(1)]
        X(:,J)=column
        return X
    

SyntaxError: invalid syntax (<ipython-input-68-e250bbd514d0>, line 22)

In [71]:
import numpy as np

def jd(self,X,p=1):
    
    n = np.size(X[:,1]) #the number of rows in X in the first column
    d = np.zeros((n*(n-1)//2))
    
    for i in range(1,n-1):
        for j in range(i+1,n):
            d((i-1)*n-(i-1)*i/2+j-i)= np.linalg.norm(X[i,:]-X[j,:],p)
    distinct_d = np.unique(d)
    
    J = np.zeros(np.size(distinct_d))
    
    for i in range(1,np.length(distinct_d)):
        J(i) = np.sum(ismember(d,distinct_d(i)))
        
    return J,distinct_d
    
    
def ismember(a, b):
    bind = {}
    for i, elt in enumerate(b):
        if elt not in bind:
            bind[elt] = i
    return [bind.get(itm, None) for itm in a] 
    

SyntaxError: can't assign to function call (<ipython-input-71-488e4a5d3863>, line 10)

In [3]:



def halton_sequence(size, dim):
    seq = []
    primeGen = next_prime()
    next(primeGen)
    for d in range(dim):
        base = next(primeGen)
        seq.append([vdc(i, base) for i in range(size)])
    return seq

def vdc(n, base=2):
    vdc, denom = 0, 1
    while n:
        denom *= base
        n, remainder = divmod(n, base)
        vdc += remainder/float(denom)
    return vdc

def next_prime():
    def is_prime(num):
        "Checks if num is a prime value"
        for i in range(2,int(num**0.5)+1):
            if(num % i)==0: return False
        return True

    prime = 3
    while(1):
        if is_prime(prime):
            yield prime
        prime += 2

In [4]:
halton_sequence(10,3)


[[0,
  0.2,
  0.4,
  0.6,
  0.8,
  0.04,
  0.24000000000000002,
  0.44,
  0.64,
  0.8400000000000001],
 [0,
  0.14285714285714285,
  0.2857142857142857,
  0.42857142857142855,
  0.5714285714285714,
  0.7142857142857143,
  0.8571428571428571,
  0.02040816326530612,
  0.16326530612244897,
  0.30612244897959184],
 [0,
  0.09090909090909091,
  0.18181818181818182,
  0.2727272727272727,
  0.36363636363636365,
  0.45454545454545453,
  0.5454545454545454,
  0.6363636363636364,
  0.7272727272727273,
  0.8181818181818182]]

In [11]:
for i in a:
    print(a[i])

0
1
2


In [18]:
import numpy as np
np.random.permutation(10)


array([4, 2, 5, 1, 8, 9, 0, 7, 3, 6])

In [24]:
import numpy as np

np.random.permutation(np.arange(1,11,1))


array([ 5,  6,  7,  4,  3,  1,  9,  8,  2, 10])

In [31]:
import numpy as np
np.linspace(0,1,10)

array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
        0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ])

In [46]:
def frange(x, y, jump):
  while x < y:
    yield x
    x += jump
a = list(a)
a= frange (0,1,0.1)

print (a[2])

TypeError: 'generator' object is not subscriptable

In [54]:
a=map(lambda x: x/10.0, range(0, 11, 1))
print(list(a))

[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]


In [64]:
import numpy as np
np.ones(5,'float',1)

array([ 1.,  1.,  1.,  1.,  1.])